spring.application.name=backend
server.port=8080

# MongoDB Configuration Placeholder
spring.data.mongodb.uri=mongodb+srv://hacknestspringboot:hacknestspringboot@firstdatabaseatlas.v1xl8.mongodb.net/hacknest?appName=firstdatabaseatlas

jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIEpXVCBzaWduYXR1cmUgbWFrZSBpdCBsb25nZXI=
jwt.expiration=86400000
